PARAMS:
  BATCH_SIZE: 8
  EPOCH: 500
  N_SAMPLE: 1
  INPUT_FRAME: 4
  OUTPUT_FRAME: 6
  COVERAGE: 0.75
  CROP_SIZE: 256
  PARSER:
    FUNCTION: data_parser
    PARAMS:
      SCALE: 32
      OFFSET: 0
      RAIN_TH: 0.01
      RAIN2DBZ: True
      MIN_VALUE: -9
  NORMALIZER:
    FUNCTION: min_max_normalizer
    PARAMS:
      MIN_VALUE: -9
      MAX_VALUE: 60
GENERATOR:
  MODEL: 
    FUNCTION: DGMRGenerator
    PARAMS:
  LOSS:
    FUNCTION: PixelWiseRegularizer
    PARAMS:
      LAMBDA: 20
      MIN_VALUE: 0.2
      MAX_VALUE: 1.5
  OPTIMIZER:
    FUNCTION: Adam
    PARAMS:
      LR: 0.00005
      BETAS: [0., 0.999]
  SCHEDULER:
    FUNCTION: 
    PARAMS:
DISCRIMINATOR:
  ITER:
  MODEL:
    FUNCTION:
    PARAMS:
  LOSS:
    FUNCTION:
    PARAMS:
  OPTIMIZER:
    FUNCTION:
    PARAMS:
  SCHEDULER:
    FUNCTION:
    PARAMS:
EVALUATION:
  THRESHOLDS: [5, 10, 20, 30]
  POOLING_SCALES: [1, 4, 16]
TRAIN:
  VAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
VAL:
  BATCH_SIZE: 16
TEST:
  BATCH_SIZE: 1
DATALOADER:
  NUM_WORKERS: 32
  PIN_MEMORY: True
SETTINGS:
  IMPORT_CKPT_PATH: 
  NUM_GPUS: 1
  RNG_SEED: 0
  DATA_PATH: /home/yihan/yh/research/Nimrod/Nimrod_2018.dat
  DATA_TYPE: int16
  DATA_SHAPE: [105120, 512, 512]
  RAIN_RECORD_PATH:
TENSORBOARD:
  SAVE_DIR: /home/yihan/yh
  VERSION: DGMR-NGAN